# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Device-USB-PanicButton
version:      0.03
version_from: lib/Device/USB/PanicButton.pm
installdirs:  site
requires:
    Device::USB:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
